<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>MinesweeperWF.Program</StartupObject>
    <ApplicationIcon>bomb.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="bomb.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <PackageReference Include="Microsoft.WinForms.Designer.SDK" Version="1.6.0" />
  </ItemGroup>

</Project>